### ISSUE TITLE
Como ejecutar la tarea y error renderización

### ISSUE THREAD

**Issue by panchouc** [IIC2513/Syllabus-S1#38]
Hola, estaba viendo los archivos de la tarea y tengo duda en varias cosas. La primera de ellas, ¿Es normal que al utilizar `yarn dev` y al renderizar la página no se vea nada? Lo digo, porque viendo el RecipesPage tiene un `<h1>` pero no se está renderizando

![image](https://github.com/user-attachments/assets/2562afce-d788-4254-a2ad-d556053e316c)

a continuación adjunto un pantallazo también de lo que me arroja el `npm list`
![image](https://github.com/user-attachments/assets/5c55c5dd-1b8e-406d-b9a6-829a241f9e8c)

¿Hay algo que me esté faltando, o que esté ignorando respecto a la ejecución de la tarea? O si quizás me falta alguna librería o algo por el estilo

**Comment by ignacio-quera** [comment]
Hola!
El index.css tiene un propiedad de color en body, la cual se nos paso quitar que hace que no se vea el texto. Eliminando esta propiedad deberia hacer que se vea lo que vayan escribiendo. Recuerda que tambien se puede cambiar las propiedades de estilo dentro de cada archivo para ajustar su pagina!
