### ISSUE TITLE
Error 500 al enviar requests a la API

### ISSUE THREAD

**Issue by IgnacioM4rtinez** [IIC2513/Syllabus-S1#43]
Hola, tengo un problema al cargar las recetas en la tarea, ya que aparece un error 500 al enviar las solicitudes correspondientes, y que servían perfectamente esta mañana.

**Comment by empanad4z** [comment]
También me pasa. Aunque funciona si pones un page_size menor a la cantidad de recetas que esta entregando actualmente el servidor. El get por defecto usa un page_size de 10 pero si pongo en los parametros, por ejemplo, page_size:6 si funciona. Ahora bien, no sé si se espera que manejemos eso o es un error del server :(
